version: '3'
services:
    mp-rss:
        image: fiware/biz-ecosystem-rss:v7.8.0
        container_name: mp-rss
        #restart: always
        #ports:
        #    - 9999:8080
        #    - 4444:4848
        #    - 1111:8181
        #links:
        #    - mp-mysql
        #depends_on:
        #    - mp-mysql
        #    - mp-apis
        networks:
            marketplace:
                aliases:
                    - mp-rss.docker
        # volumes:
        #    - ./rss-conf:/etc/default/rss  # Used if not configured by environment
        environment:
            - MYSQL_HOST=mp-mysql.docker
            - MYSQL_PORT=3306
            - BAE_RSS_DATABASE_URL=jdbc:mysql://mp-mysql.docker:3306/RSS
            - BAE_RSS_DATABASE_USERNAME=root
            - BAE_RSS_DATABASE_PASSWORD=root
            - BAE_RSS_DATABASE_DRIVERCLASSNAME=com.mysql.jdbc.Driver
            - BAE_RSS_OAUTH_CONFIG_GRANTEDROLE=admin
            - BAE_RSS_OAUTH_CONFIG_SELLERROLE=seller
            - BAE_RSS_OAUTH_CONFIG_AGGREGATORROLE=Aggregator


networks:
    marketplace:
      external: true
    default:
      external: true
      name: marketplace
