version: '3'
services:
    mp-elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
        container_name: mp-elasticsearch
        environment:
            - discovery.type=single-node
            # - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            # ulimits:
            #   memlock:
            #       soft: -1
            #       hard: -1
        ports:
            - "127.0.0.1:9200:9200"
        networks:
            marketplace:
              aliases:
                - mp-elasticsearch.docker

    mp-mongo:
        image: mongo:3.6.21
        container_name: mp-mongo
        networks:
            marketplace:
                aliases:
                    - mp-mongo.docker
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
            #MONGO_INITDB_DATABASE: root_db
        volumes:
            - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
            # Uncomment for data persistance
            - ./mongo-data:/data/db

    mp-mysql:
        image: mysql:5.7
        container_name: mp-mysql
        volumes:
            #- ./init-mysql.sql:/docker-entrypoint-initdb.d/init-mysql.sql
            # Uncomment for data persistance
            - ./mysql-data:/var/lib/mysql
        networks:
            marketplace:
                aliases:
                    - mp-mysql.docker
        environment:
            - MYSQL_ROOT_PASSWORD=root
            #- MYSQL_DATABASE=RSS


networks:
    marketplace:
      external: true
    default:
      external: true
      name: marketplace
